NIFTY_50 = {
    "Adani Enterprises": "ADANIENT.BSE",
    "Adani Ports": "ADANIPORTS.BSE",
    "Apollo Hospitals": "APOLLOHOSP.BSE",
    "Asian Paints": "ASIANPAINT.BSE",
    "Axis Bank": "AXISBANK.BSE",
    "Bajaj Auto": "BAJAJ-AUTO.BSE",
    "Bajaj Finance": "BAJFINANCE.BSE",
    "Bajaj Finserv": "BAJAJFINSV.BSE",
    "Bharti Airtel": "BHARTIARTL.BSE",
    "BPCL": "BPCL.BSE",
    "Britannia": "BRITANNIA.BSE",
    "Cipla": "CIPLA.BSE",
    "Coal India": "COALINDIA.BSE",
    "Divi's Laboratories": "DIVISLAB.BSE",
    "Dr. Reddy's Laboratories": "DRREDDY.BSE",
    "Eicher Motors": "EICHERMOT.BSE",
    "Grasim Industries": "GRASIM.BSE",
    "HCL Technologies": "HCLTECH.BSE",
    "HDFC Bank": "HDFCBANK.BSE",
    "HDFC Life Insurance": "HDFCLIFE.BSE",
    "Hero MotoCorp": "HEROMOTOCO.BSE",
    "Hindalco Industries": "HINDALCO.BSE",
    "Hindustan Unilever": "HINDUNILVR.BSE",
    "ICICI Bank": "ICICIBANK.BSE",
    "IndusInd Bank": "INDUSINDBK.BSE",
    "Infosys": "INFY.BSE",
    "ITC": "ITC.BSE",
    "JSW Steel": "JSWSTEEL.BSE",
    "Kotak Mahindra Bank": "KOTAKBANK.BSE",
    "Larsen & Toubro": "LT.BSE",
    "Mahindra & Mahindra": "M&M.BSE",
    "Maruti Suzuki": "MARUTI.BSE",
    "NTPC": "NTPC.BSE",
    "Nestle India": "NESTLEIND.BSE",
    "ONGC": "ONGC.BSE",
    "Power Grid Corporation": "POWERGRID.BSE",
    "Reliance Industries": "RELIANCE.BSE",
    "SBI Life Insurance": "SBILIFE.BSE",
    "Shriram Finance": "SHRIRAMFIN.BSE",
    "State Bank of India": "SBIN.BSE",
    "Sun Pharmaceutical": "SUNPHARMA.BSE",
    "Tata Consultancy Services": "TCS.BSE",
    "Tata Consumer Products": "TATACONSUM.BSE",
    "Tata Motors": "TATAMOTORS.BSE",
    "Tata Steel": "TATASTEEL.BSE",
    "Tech Mahindra": "TECHM.BSE",
    "Titan Company": "TITAN.BSE",
    "Trent": "TRENT.BSE",
    "UltraTech Cement": "ULTRACEMCO.BSE",
    "Wipro": "WIPRO.BSE",
}
